### ISSUE TITLE
Ship on Flathub

### ISSUE THREAD

**Issue by cassidyjames** [HarmonyHoney/ROTA#6]
I recently came across your game and absolutely love it; it's unique, challenging, and super cute. First of all: nice work! And thank you so much for open sourcing it.

I'm a volunteer at [Flathub](https://flathub.org/about), the defacto indie Linux app store that ships out of the box on many Linux-based OSes including the Steam Deck desktop mode. I've started to explore if I can automate the Linux build of ROTA to get it onto Flathub so more people can play it (and because I personally think quality games are a great category of apps that Flathub is currently lacking). Relevant PR: https://github.com/HarmonyHoney/ROTA/pull/5

I _think_ due to the open licensing, I could just ship it there—but I wanted to check a couple of things, first:

1. Each app/game on Flathub needs a unique [RDNN](https://en.wikipedia.org/wiki/Reverse_domain_name_notation)-prefixed app ID; **would it make more sense to use `net.hhoney.rota`, or `io.github.harmonyhoney.rota`?** Either is technically fine and I personally prefer the conciseness of the former, but I wanted to check in with you, first.

2. **Would you have any interest in verifying the game on Flathub?** [Verification](https://docs.flathub.org/docs/for-app-authors/verification) is super easy, and it's just a way to show end users that the ROTA on Flathub is actually the ROTA you've made and not some knock-off malware-infested version or something. :P More details at the link, but the easiest way is to drop a unique token in a .well-known file on your website.

I can totally help answer any questions about Flathub or verification, too, if you're interested! 

_Aside: I'm also an employee at the non-profit [Endless Foundation](https://www.endlessos.org/game-making) where we use game development and Godot Engine specifically to build and nurture learners' soft skills like collaboration, problem decomposition, and project management in addition to helping expose those learners to what you'd expect like coding and art/design—if you were at or followed [GodotCon 24](https://godotengine.org/article/review-godotcon24/), we were gold sponsors and had our team there presenting our open source Block Coding plugin. I'm pursuing getting ROTA onto Flathub for personal reasons, but it does align well with what we're doing at Endless, and since Endless OS ships with Flathub out of the box, it would mean ROTA would be more easily installable there, too. :)_

**Comment by HarmonyHoney** [comment]
Hello Cassidy !
Thank you for all the kind words and contributions to ROTA (-=
I love Flathub & have experience using it with Linux !

1: Yes i agree the RDNN of net.hhoney.rota is concise & a good pick

2: Absolutely I want to verify the game !
Hopefully we can make it work, my hhoney.net url is a redirect to my harmonyhoney.github.io hosted website.

Sweet I may have a question or two, I see you in the HHoney discord server now !

**Comment by HarmonyHoney** [comment]
I merged you requests ! Thank you (: 
How can I use this to make a build for Flathub ?
I saw the godot-ci thing you linked - https://hub.docker.com/r/smks/godot-ci/tags
do i use this to make a build ?

**Comment by cassidyjames** [comment]
@HarmonyHoney sorry about replying in like three different places! I'm working on proposing the manifest to the Flathub org, which will get some review/feedback and then be merged if approved.

I think the next steps from your side is just to [create a release](https://github.com/HarmonyHoney/ROTA/releases) here on GitHub, with whatever version number makes sense to you. That will be the version we point the Flatpak manifest at.

**Comment by HarmonyHoney** [comment]
Right on ! Thanks @cassidyjames 
I've created a Release and Tag for Flathub now (:
https://github.com/HarmonyHoney/ROTA/releases/tag/Flathub

let me know what our next step is !

**Comment by cassidyjames** [comment]
Thanks! I've proposed the manifest to Flathub: https://github.com/flathub/flathub/pull/5908

For future releases it probably makes more sense to use the game's version number as the git tag for the release, e.g. `1.9` for version 1, patch 9 (see: [Semantic Versioning](https://semver.org/)). We'll see if the reviewers complain about that, or if they're fine with the `Flathub` tag name.

**Comment by cassidyjames** [comment]
Update: yep, they've requested a clearly-versioned tag for the release. @HarmonyHoney could you make a release with e.g. a `1.9` tag (or `1.10` if you'd consider this patch 10)?

**Comment by cassidyjames** [comment]
The manifest repo has been merged as-is (https://github.com/flathub/net.hhoney.rota), but we should still update it with a versioned tag when we get a chance. But I think this issue can be considered closed, as it's being deployed to Flathub today. :)
