### ISSUE TITLE
Phone support

### ISSUE THREAD

**Issue by Henry-Hiles** [HarmonyHoney/ROTA#9]
Hello! I just installed this game on my linux phone, its so cool! Unfortunately, I can't control it without the keyboard. It would be amazing if the menu could be interacted with through touch, and if there could be an overlay for controls. Thanks!

**Comment by cassidyjames** [comment]
@Henry-Hiles considering there's an Android build, I wonder if the Linux export isn't setting touch up correctly. 🤔 Alternately, the fact that it's running under X11 (or XWayland) could affect touch controls? Not sure. I can poke at it on my touch laptop to see if I can reproduce this there compared to the Android build.

**Comment by HarmonyHoney** [comment]
Hello Henry !

Turn "Touch Screen" to ON in the settings.
This is available in all builds (:

![image](https://github.com/user-attachments/assets/21d5872f-5e82-4d65-a822-b147c4500655)

**Comment by Henry-Hiles** [comment]
Oh! Can I get to that though?

**Comment by Henry-Hiles** [comment]
I'll check later but I think I couldn't hit any buttons in the ui.

**Comment by Henry-Hiles** [comment]
Yeah, but i was able to turn on touchscreen using the onscreen keyboard and that works. Maybe it can be turned on by default in certain cases or something?

**Comment by HarmonyHoney** [comment]
i made an update that will save your last Touch Screen option between game sessions!

so if you played with touch screen ON before, the game will start with it ON

**Comment by cassidyjames** [comment]
@HarmonyHoney I think the specific issue here is that @Henry-Hiles is using a device that doesn't have a physical keyboard, just a touch screen (e.g. a Linux phone). I wonder if Godot has some sort of device detection and could turn on the touch controls by default for devices that don't have a physical keyboard/mouse, or if that information is even being communicated correctly from the OS to the Godot Engine in this case. 🤔

Another idea (albeit a workaround and maybe more involved) could be a small "touch controls" toggle button in the corner that's always present on the initial screen, so anyone could toggle them on via touch from the start screen.

**Comment by Henry-Hiles** [comment]
Thats correct, I'm on a linux phone, so it was a struggle getting to settings in the first place. Either a toggle like Cassidy said, or a dialogue popup on first launch would work IMO.

**Comment by HarmonyHoney** [comment]
Hello Henry !
I've released a new version that will bring up the touch controls after tapping the screen automatically.
let me know how this works for you.

https://github.com/HarmonyHoney/ROTA/releases/tag/something

thanks !

**Comment by Henry-Hiles** [comment]
Great, thanks! I'll try it tonight.

**Comment by Henry-Hiles** [comment]
Do you have a flatpak build anywhere?

**Comment by Henry-Hiles** [comment]
Maybe a github action that provides a .flatpak file would be good.

**Comment by HarmonyHoney** [comment]
sweet i believe cassidy wants to implement that

**Comment by Henry-Hiles** [comment]
:+1:, i cant really test until a flatpak with the touchscreen change is available

**Comment by cassidyjames** [comment]
@Henry-Hiles I went ahead and pushed the latest tag to Flathub; can you update from there and report back?

**Comment by cassidyjames** [comment]
I've tested on my touchscreen Linux laptop and the controls show up as expected when I touch the screen. Smart!

**Comment by Henry-Hiles** [comment]
Works perfectly, thank you!
